### ISSUE TITLE
Sampler keeps reloading

### ISSUE THREAD

**Issue by sysads** [roaminggamer/SSKCorona#1]
Hi Ed

Thanks for this brilliant work.

When I load the sampler on simulator, it keeps reloading back to main screen. I see this repeated in console:

WARNING: display.setStatusBarMode() not supported in the simulator for GT-I9300
device

**Comment by roaminggamer** [comment]
Hi!  I just committed an update (22 MAY 2015) that should fix the 'reloading' loop issue.  

Please let me know  if you still encounter this problem.

**Comment by roaminggamer** [comment]
I'm going to close this now.  Please open a new issue if you encounter more problems.

**Comment by sysads** [comment]
Sure and thanks
